[package]
name = "mdcr"
version = "0.5.0"
edition = "2024"
description = "Validate, execute and optionally rewrite code blocks in Markdown files based on arbitrary commands"
readme = "README.md"
license = "EUPL-1.2"
repository = "https://github.com/drupol/markdown-code-runner"
keywords = [
  "cli",
  "markdown",
  "parser",
  "linter",
]

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["cargo", "derive"] }
env_logger = "0.11.10"
log = "0.4.29"
pulldown-cmark-codeblock = { version = "0.1.0" }
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3"
toml = { version = "1.1", features = ["parse"] }
walkdir = "2.5.0"

[[bin]]
name = "mdcr"
path = "src/main.rs"

[profile.release]
strip = true
